cookie:
  secure: true  # 프로덕션 기본값 (HTTPS 필수)
  same-site: None

spring:
  application:
    name: bssm_dev

  # JPA DataSource Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bssm_dev?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: bdv
    password: Kdoornega0128!

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/bssm_dev
      auto-index-creation: true
      transaction:
        enabled: true

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:mysql://localhost:3306/bssm_dev
    username: bdv
    password: Kdoornega0128!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false  # dev에서만 true