cookie:
  secure: true  # 프로덕션 기본값 (HTTPS 필수)
  same-site: None

spring:
  application:
    name: bssm_dev

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/bssm_dev
      auto-index-creation: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false  # dev에서만 true